POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl" : "https://www.flipkart.com/realme-narzo-30-pro-5g-sword-black-128-gb/p/itm8cb3552276c44?pid=MOBGYFAXM6ARMYGS&lid=LSTMOBGYFAXM6ARMYGSCL72HX&marketplace=FLIPKART&store=tyy%2F4io&srno=b_1_1&otracker=clp_metro_expandable_3_3.metroExpandable.METRO_EXPANDABLE_Shop%2BNow_mobile-phones-store_YELWEWN3DMAC_wp2&fm=neo%2Fmerchandising&iid=b3de4659-b629-4260-9302-3d7c482aabe7.MOBGYFAXM6ARMYGS.SEARCH&ppt=clp&ppn=mobile-phones-store&ssid=co5qdqsgtc0000001654189088741"

}